const mcCodeToCrowdin: {[key: string]: string} = {};

function add(mcCode: string, crowdinCode: string) {
  mcCodeToCrowdin[mcCode] = crowdinCode;
}

add("af_za", "af");
add("ar_sa", "ar");
add("ast_es", "ast");
add("az_az", "az");
add("ba_ru", "ba");
add("be_by", "be");
add("bg_bg", "bg");
add("br_fr", "br-FR");
add("bs_ba", "bs");
add("ca_es", "ca");
add("cs_cz", "cs");
add("cy_gb", "cy");
add("da_dk", "da");
add("de_at", "de-AT");
add("de_ch", "de-CH");
add("de_de", "de");
add("el_gr", "el");
add("en_au", "en-AU");
add("en_ca", "en-CA");
add("en_gb", "en-GB");
add("en_nz", "en-NZ");
add("en_pt", "en-PT");
add("en_ud", "en-UD");
add("en_us", "en-US");
add("en_ws", "en-WS");
add("en_7s", "en-PT");
add("en_ud", "en-UD");
add("eo_uy", "eo");
add("es_ar", "es-AR");
add("es_cl", "es-CL");
add("es_ec", "es-EC");
add("es_es", "es-ES");
add("es_mx", "es-MX");
add("es_uy", "es-UY");
add("es_ve", "es-VE");
add("et_ee", "et");
add("eu_es", "eu");
add("fa_ir", "fa");
add("fi_fi", "fi");
add("fil_ph", "fil");
add("fo_fo", "fo");
add("fr_ca", "fr-CA");
add("fr_fr", "fr");
add("fra_de", "fra-DE");
add("fy_nl", "fy-NL");
add("ga_ie", "ga-IE");
add("gd_gb", "gd");
add("gl_es", "gl");
add("haw_us", "haw");
add("he_il", "he");
add("hi_in", "hi");
add("hr_hr", "hr");
add("hu_hu", "hu");
add("hy_am", "hy-AM");
add("id_id", "id");
add("ig_ng", "ig");
add("io_en", "ido");
add("is_is", "is");
add("it_it", "it");
add("ja_jp", "ja");
add("jbo_en", "jbo");
add("ka_ge", "ka");
add("kk_kz", "kk");
add("kn_in", "kn");
add("ko_kr", "ko");
add("kw_gb", "kw");
add("la_la", "la-LA");
add("lb_lu", "lb");
add("li_li", "li");
add("lol_us", "lol");
add("lt_lt", "lt");
add("lv_lv", "lv");
add("mi_NZ", "mi");
add("mk_mk", "mk");
add("mn_mn", "mn");
add("ms_my", "ms");
add("mt_mt", "mt");
add("nds_de", "nds");
add("nl_be", "nl-BE");
add("nl_nl", "nl");
add("nn_no", "nn-NO");
add("no_no", "no");
add("oc_fr", "oc");
add("pl_pl", "pl");
add("pt_br", "pt-BR");
add("pt_pt", "pt-PT");
add("qya_aa", "qya-AA");
add("ro_ro", "ro");
add("ru_ru", "ru");
add("se_no", "se");
add("sk_sk", "sk");
add("sl_si", "sl");
add("so_so", "so");
add("sq_al", "sq");
add("sr_sp", "sr");
add("sv_se", "sv-SE");
add("ta_in", "ta");
add("th_th", "th");
add("tl_ph", "tl");
add("tlh_aa", "tlh-AA");
add("tr_tr", "tr");
add("tt_ru", "tt-RU");
add("uk_ua", "uk");
add("val_es", "val-ES");
add("vec_it", "vec");
add("vi_vn", "vi");
add("yi_de", "yi");
add("yo_ng", "yo");
add("zh_cn", "zh-CN");
add("zh_hk", "zh-HK");
add("zh_tw", "zh-TW");

export function convertLanguageCode(mcCode: string): string | undefined {
  return mcCodeToCrowdin[mcCode];
}

export function convertLanguageCodes(mcCodes: string[]): string[] {
  // return mcCodes.map(convertLanguageCode).filter((code) => code);
  return mcCodes.map(convertLanguageCode).filter((code: string | undefined) => code !== undefined) as string[];
}